### ISSUE TITLE
GitVersion Task 0.9.3 failing with Unhandled: Invalid regular expression: /*.local/: Nothing to repeat

### ISSUE THREAD

**Issue by bmkATfs** [GitTools/actions#107]
running on azure devops on prem:

##[debug]Evaluating condition for step: 'gitversion/execute'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: gitversion/execute
==============================================================================
Task         : Execute GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
Version      : 0.9.3
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
##[debug]agent.TempDirectory=D:\vsts-agent\_work\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_CONFIGFILEPATH
##[debug]loading INPUT_UPDATEASSEMBLYINFO
##[debug]loading INPUT_USECONFIGFILE
##[debug]loading SECRET_AGENT_PROXYPASSWORD
##[debug]loaded 7
##[debug]Agent.ProxyUrl=http://x.x.x.x:8080
##[debug]Agent.ProxyUsername=dddxxx
##[debug]Agent.ProxyPassword=***
##[debug]Agent.ProxyBypassList=["tfs\\.t-fs01\\.vwfs-ad","tfs2010-test\\.t-fs01\\.vwfs-ad","10\\.((1?\\d?\\d|25[0-5]|2[0-4]\\d)(\\.|$)){3}",".*\\.local",".*\\.external",".*\\.vwf\\.vwfs-ad",".*\\.d-fs01\\.d-vwf\\.d-vwfs-ad",".*\\.t-fs01\\.vwfs-ad"]
##[debug]Agent.TempDirectory=D:\vsts-agent\_work\_temp
##[debug]expose agent proxy configuration.
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]Agent.ProxyUrl=http://x.x.x.x:8080
##[debug]Agent.ProxyUsername=dddxxx
##[debug]Agent.ProxyPassword=***
##[debug]Agent.ProxyBypassList=["tfs\\.t-fs01\\.vwfs-ad","tfs2010-test\\.t-fs01\\.vwfs-ad","10\\.((1?\\d?\\d|25[0-5]|2[0-4]\\d)(\\.|$)){3}",".*\\.local",".*\\.external",".*\\.vwf\\.vwfs-ad",".*\\.d-fs01\\.d-vwf\\.d-vwfs-ad",".*\\.t-fs01\\.vwfs-ad"]
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : D:\vsts-agent\_work\_tasks\gitversion\execute_9013cf7f-ee8d-49f4-a39b-db244928d391\0.9.3\lib.json
##[debug]adding resource file: D:\vsts-agent\_work\_tasks\gitversion\execute_9013cf7f-ee8d-49f4-a39b-db244928d391\0.9.3\lib.json
##[debug]system.culture=en-US
##[debug]Agent.ProxyUrl=http://x.x.x.x:8080
##[debug]Agent.ProxyUsername=dddxxx
##[debug]Agent.ProxyPassword=***
##[debug]Agent.ProxyBypassList=["tfs\\.t-fs01\\.vwfs-ad","tfs2010-test\\.t-fs01\\.vwfs-ad","10\\.((1?\\d?\\d|25[0-5]|2[0-4]\\d)(\\.|$)){3}",".*\\.local",".*\\.external",".*\\.vwf\\.vwfs-ad",".*\\.d-fs01\\.d-vwf\\.d-vwfs-ad",".*\\.t-fs01\\.vwfs-ad"]
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]task result: Failed
##[error]Unhandled: Invalid regular expression: /*.local/: Nothing to repeat
##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Invalid regular expression: /*.local/: Nothing to repeat
##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Invalid regular expression: /*.local/: Nothing to repeat
##[section]Finishing: gitversion/execute

assuming that the task is failing on the ProxyBypassList,

**Comment by craigjar** [comment]
Any resolution for this issue?  I have the same issue with UniversalPackages publish command.  Agent is also running behind a proxy and has a *.<domain name> entry.

**Comment by bmkATfs** [comment]
I'm using GitVersion-Task Version 5 with the bundled version. Update via Proxy is not possible.....

YAML:

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@5
  displayName: GitVersion
  inputs:
    updateAssemblyInfo: true
    additionalArguments: /diag

**Comment by craigjar** [comment]
I found the following workaround for my issue.  Putting the following variable definition at the root of the yaml config did the trick:

```
variables: {
    # Need to override no_proxy and AGENT_PROXYBYPASSLIST due to bug in DevOps trying to parse as regular expressions
    # *.<domain name> results in Error: "Unhandled: Invalid regular expression: /*.<domain name>/: Nothing to repeat"
  no_proxy: '',
  AGENT_PROXYBYPASSLIST: ''
}
```
