### ISSUE TITLE
[ISSUE]: GRM publish uses incorrect labels

### ISSUE THREAD

**Issue by mkevenaar** [GitTools/actions#1183]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

According to the [manifest](https://github.com/GitTools/actions/blob/main/gitreleasemanager/publish/action.yml#L23-L26), `milestone` is required. However, GRM uses `tagName`. This is also required to be able to get the module to work.

```PowerShell
PS > grm help publish
GitReleaseManager 0.18.0+e46787339c6740cc14a8b9c83181b7cf70900865
Copyright (C) 2024 GitReleaseManager

  -t, --tagName            Required. The name of the release (Typically this is the generated SemVer Version Number).

  --token                  Required. The Access Token to access Version Control System with.

  -o, --owner              Required. The owner of the repository.

  -r, --repository         Required. The name of the repository.

  --provider               (Default: GitHub) Version Control System provider

  --debug                  Enable debugging console output

  -l, --logFilePath        Path to where log file should be created. Defaults to logging to console.

  --no-logo                Disables the generation of the GRM commandline logo.

  -d, --targetDirectory    The directory on which GitReleaseManager should be executed. Defaults to current directory.

  --verbose                Enable verbose console output

  --ci                     Configure GitReleaseManager to be compatible with CI systems

  --help                   Display this help screen.
  ```

### What is expected?

Action to be using `tagName`

### Steps to Reproduce

See https://github.com/mkevenaar/CharlieSpring/blob/develop/.github/workflows/release.yaml

**Comment by mkevenaar** [comment]
In fact, the example shows exactly this: https://github.com/GitTools/actions/blob/main/docs/examples/github/gitreleasemanager/publish.md

**Comment by mkevenaar** [comment]
Duplicate of #1137

Only change that is incorrect would be the example

**Comment by arturcic** [comment]
@mkevenaar thanks for finding it, will be fixed in the next release

**Comment by arturcic** [comment]
@mkevenaar v2.0.1 released
