### ISSUE TITLE
[ISSUE]: Getting "A supported task execution handler was not found." on setup of GitVersion

### ISSUE THREAD

**Issue by rodeoboy** [GitTools/actions#1231]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### What are you seeing?

I am trying to set up gitversion in an ADO Server pipeline. I installed the gittools from the marketplace and I am getting the following error when I run the build.

##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.

### What is expected?

Setup of a version of gitversion that runs on x64

### Steps to Reproduce

I have setup git version in my build script as shown below.

jobs:
- job: Build
  displayName: Build
  continueOnError: false
  workspace:
    clean: all
  steps:
    - checkout: self
      fetchDepth: 0

    - task: gitversion/setup@3
      displayName: Install GitVersion
      inputs:
        versionSpec: '5.12.0'

    - task: gitversion/execute@3
      displayName: Determine Version
      inputs:
        updateAssemblyInfo: true

### Output log or link to your CI build (if appropriate).

```shell
2024-08-19T20:46:13.9147963Z ##[section]Starting: Install GitVersion
2024-08-19T20:46:13.9500092Z ==============================================================================
2024-08-19T20:46:13.9500331Z Task         : Setup GitVersion Task
2024-08-19T20:46:13.9500411Z Description  : Easy Semantic Versioning (https://semver.org) for projects using Git
2024-08-19T20:46:13.9500588Z Version      : 3.0.0
2024-08-19T20:46:13.9500654Z Author       : GitTools Contributors
2024-08-19T20:46:13.9500733Z Help         : See the [documentation](https://gitversion.net/docs/) for help
2024-08-19T20:46:13.9500839Z ==============================================================================
2024-08-19T20:46:13.9933734Z ##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.
2024-08-19T20:46:13.9947583Z ##[section]Finishing: Install GitVersion
```

**Comment by dreteddy** [comment]
Same issue on self hosted windows agent. Works on self hosted ubuntu agent and MS hosted agents

**Comment by willibrandon** [comment]
I just bumped into this issue myself.

**Comment by shieldsjared** [comment]
Also running into this. A _quick google_ didnt lead me to a work around either. :/

**Comment by arturcic** [comment]
@rodeoboy @dreteddy @willibrandon @shieldsjared that could be because of the agent version. We currently support https://github.com/GitTools/actions/blob/13ffcf7b6246fa3632dcaa40990b9ee09f1879d6/dist/azure/updateTasks.mjs#L32

**Comment by arturcic** [comment]
Can you tell me which version of the agents you have?

**Comment by rodeoboy** [comment]
3.225.2
Is there any value in installing the gitversion dotnet tool directly to the self hosted build agent?

**Comment by arturcic** [comment]
> 3.225.2
> Is there any value in installing the gitversion dotnet tool directly to the self hosted build agent?

The tasks/actions are just opinionated wrappers of the tools. You can run the tools directly in your pipeline/workflow

**Comment by shieldsjared** [comment]
> Can you tell me which version of the agents you have?

@arturcic - I've also got version `3.225.2`.

**Comment by arturcic** [comment]
> > Can you tell me which version of the agents you have?
> 
> @arturcic - I've also got version `3.225.2`.

It seems to be an issue with the agent, and probably the version of nodejs https://github.com/microsoft/powerplatform-build-tools/issues/491#issuecomment-1691826544

**Comment by arturcic** [comment]
Can you check which version of nodejs you have? As the requirements are https://github.com/GitTools/actions/blob/main/dist%2Fazure%2Fgitversion%2Fsetup%2Ftask.json#L17

**Comment by shieldsjared** [comment]
@arturcic - 

We've got build agent version `3.225.2` and NodeJS version `20.17.0`.  We initially had v16 (whoops!) but after upgrading to 20, we're still getting the issue.

After reviewing the extension code that you pointed out, it appears that this issue is something _deeper_ than the gittools extension and likely something to do w/ the overall AzDO extension framework, so I'll keep at it. Appreciate the pointers!

**Comment by arturcic** [comment]
@shieldsjared thanks for the updates, I will close this issue then as it's not related to gittools/actions
