### ISSUE TITLE
[ISSUE]: "AdditionalArguments" removed without proper replacement for /updatewixversionfile

### ISSUE THREAD

**Issue by freakalot** [GitTools/actions#1293]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### What are you seeing?

In the gitversion execute task for Azure Devops, the parameter to set additional attrinutes has been removed in version 3.0.0. Now it is not possible to generate the version file for wix anymore which is a viable option of gitversion as there is no specific parameter to activate this option. This breaks our build pipelines and makes the execute task useless for our project.

We use Azure DevOps but as far as I can see in this commit, this issue also applies to the github action: [affected commit](https://github.com/GitTools/actions/commit/da21e58e55c27ade894dab7c390a5cc3213a7552)

### What is expected?

either bring back the flexibility with the AdditionalArguments parameter or introduce a soecific parameter to the DevOps task to generate the version file for wix.

### Steps to Reproduce

Create a pipeline and try to set the /updatewixversionfile parameter for the gitversion/execute@3.0.0 task

**Comment by arturcic** [comment]
@freakalot  there is a https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/command.md option for that
