### ISSUE TITLE
[ISSUE]: Execute Gitversion version 0 creates warning

### ISSUE THREAD

**Issue by linus66** [GitTools/actions#1321]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### What are you seeing?

When using Execute gitversion task version 0, it creates a warning in the Initialize step of the job where the task is located.

##[warning]Task 'Setup GitVersion Task' version 0 (gitversion/setup@0) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

![Image](https://github.com/user-attachments/assets/1440d43f-6b6b-4a20-9820-6f5d6f799f0f)

### What is expected?

No warning

### Steps to Reproduce

Add the gitversion execute task to a job and run the pipeline

**Comment by arturcic** [comment]
Please install the latest version (https://marketplace.visualstudio.com/items?itemName=gittools.gittools)  https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/setup.md
