### ISSUE TITLE
[ISSUE]: gitversion/setup@0 azure devops task is targetting a node version that is end of life

### ISSUE THREAD

**Issue by edgarkiechle** [GitTools/actions#1347]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/GitVersion/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### GitVersion version

0

### Operating system

N/A, Linux

### What are you seeing?

When running the task 'Execute GitVersion Task' version 0 (gitversion/execute@0) on azure devops pipeline we get the following warning: 
##[warning]Task 'Execute GitVersion Task' version 0 (gitversion/execute@0) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

### What is expected?

Not receive the warning.

### Steps to Reproduce

Add the following task to a pipeline an run the pipelin

  - task: gitversion/setup@0
    displayName: "Use GitVersion ${{ parameters.GitVersionRelease }}"
    inputs:
      versionSpec: '5.x'

### Output log or link to your CI build (if appropriate).

```shell

```

**Comment by edgarkiechle** [comment]
@arturcic this extension is already installed on my organization.

**Comment by arturcic** [comment]
then just use the v3 instead

**Comment by arturcic** [comment]
https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/setup.md
