### ISSUE TITLE
Request for GitHub publisher verification for "GitTools" Action

### ISSUE THREAD

**Issue by rnoda-phsa** [GitTools/actions#1365]
Hello there,
 
We are experiencing the same situation described in the original issue:

(Applying for GitHub publisher verification for "GitTools" Action)[https://github.com/GitTools/actions/issues/732]

The verification process you reviewed in the original issue applies only to Apps, not Actions.

Have you seen this information about adding the badge to Actions in the GitHub Marketplace?

[About badges in GitHub Marketplace](https://docs.github.com/en/actions/sharing-automations/creating-actions/publishing-actions-in-github-marketplace#about-badges-in-github-marketplace)

It states that the partner organization (Action creator) needs to send an email to [partnerships@github.com](mailto:partnerships@github.com) to request the "verified creator" badge.

Would that be feasible?

Thanks!

 _Originally posted by @rnoda in [#732](https://github.com/GitTools/actions/issues/732#issuecomment-2504667970)_

**Comment by arturcic** [comment]
@asbjornu can we do that?

**Comment by arturcic** [comment]
@rnoda-phsa see ![Image](https://github.com/user-attachments/assets/5789330e-9232-4b6f-b62f-67906e14b272)

**Comment by rnoda-phsa** [comment]
This is great, thanks!
