### ISSUE TITLE
[ISSUE]: GitVersion 3.0.4 Breaking Change

### ISSUE THREAD

**Issue by ppi-kosipenko** [GitTools/actions#1393]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### What are you seeing?

The task no longer sets $(GitVersion.SemVer) pipeline variable. All my pipelines stopped working. Please fix ASAP!

### What is expected?

$(GitVersion.SemVer) is set to SemVer

### Steps to Reproduce

output $(GitVersion.SemVer) in subsequent task  to verify

### Output log or link to your CI build (if appropriate).

```shell

```

**Comment by arturcic** [comment]
Duplicate https://github.com/GitTools/actions/issues/1389
