### ISSUE TITLE
[ISSUE]: Gitversion broken when using versionSpec "6.x"

### ISSUE THREAD

**Issue by dbfr3qs** [GitTools/actions#1401]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

GitHub Actions

### What are you seeing?

Hi there, it appears that a recent release of Gitversion has broken the Gittools action when using an ambiguous spec version, e.g.:

```
uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: "6.x"
```

Latest Gitversion release is [6.1.0](https://github.com/GitTools/GitVersion/releases/tag/6.1.0).
Code causing the error to be raised [here](https://github.com/GitTools/actions/blob/bc8cf5c46deaf5b65f35d2032fc310924aacb021/src/tools/gitversion/tool.ts#L20C1-L21C1) (I think, not familiar with the codebase).

Error is:

```
Error: Version spec '6.x' resolved as '6.1.0' does not satisfy the range '>=5.2.0 <6.1.0'.See https://github.com/GitTools/actions/blob/main/docs/versions.md for more information.
```

Additionally the [docs](https://github.com/GitTools/actions/blob/main/docs/versions.md) reference v4 of this action as the only supporting action for gitversion 6.1.0+, but I can't see a v4 release.

We can get around it by pinning the versionSpec to `6.0.5` but just wanted to raise it.

### What is expected?

Either v4 of this action is available or the docs are updated to reflect that versions of Gitversion >= 6.1.0 are not supported.

### Steps to Reproduce

Try and run like so:

```
uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: "6.x"
```

### Output log or link to your CI build (if appropriate).

```shell
Error: Version spec '6.x' resolved as '6.1.0' does not satisfy the range '>=5.2.0 <6.1.0'.See https://github.com/GitTools/actions/blob/main/docs/versions.md for more information.
```

**Comment by arturcic** [comment]
Ok, this type of issue related to 6.x and task 3.1.1 is repeated already in several places. I guess the confusion is the `versions.md` file which is listing v4 (which is a planned version at this moment) as supporting version 6.1.x of the GitVersion.
In my opinion the message is self-explanatory, but I guess I need to remove the v4 from the `versions.md` file just to avoid confusions. This repository does not have the same release timeline as the GitVersion or GitReleaseManager tools, so it's not clear why the expectation is to always use the latest version. Probable we need to update the docs and in the samples just specify the `6.0.x` to avoid this issues and update the samples only when v4 is release

**Comment by dbfr3qs** [comment]
Yeah all good -  and thanks for the prompt reply. That all makes sense, I just thought I'd let you know. FWIW I reckon if you update the versions doc that's probably enough as the error message links straight to it 👍 Thanks again @arturcic

**Comment by arturcic** [comment]
https://github.com/GitTools/actions/issues/1403

**Comment by arturcic** [comment]
Closed by #1403

**Comment by rcdailey** [comment]
I've jumped around a few of these issues and I see explanations but none of it makes sense to me. I don't know why `6.x` shouldn't work; it was working fine before. I have no idea what all the v4 talk is about. Very disappointing that this doesn't work anymore.

**Comment by arturcic** [comment]
@rcdailey check this https://github.com/GitTools/actions/blob/4f8e31d7651296752fc4e082b017d785d30c4a05/docs/versions.md, you should use 6.0.x instead
