### ISSUE TITLE
[ISSUE]: Node version end of life

### ISSUE THREAD

**Issue by CezaryBD** [GitTools/actions#1408]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [issues](https://github.com/GitTools/actions/issues) to ensure it has not already been reported

### GitVersion package

AzureDevops task

### What are you seeing?

##[warning]Task 'Setup GitVersion Task' version 0 (gitversion/setup@0) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

### What is expected?

Migration to a LTS Node version.

### Steps to Reproduce

Create a pipeline with https://marketplace.visualstudio.com/items?itemName=gittools.gittools

### Output log or link to your CI build (if appropriate).

```shell

```

**Comment by arturcic** [comment]
@CezaryBD the latest version available is 3.1.1.24121015 so it's a no issue
