### ISSUE TITLE
GitVersion: /ensureassemblyinfo support

### ISSUE THREAD

**Issue by Archomeda** [GitTools/actions#220]
I had hoped that providing the additional argument /ensureassemblyinfo that GitVersion would work, but sadly it seems that the action is hardchecking the file provided in the updateAssemblyInfoFilename, effectively rendering the additional argument useless.

Would it be possible to add support for /ensureassemblyinfo without me requiring to run a custom step to create the file first?

**Comment by Archomeda** [comment]
Hello?

**Comment by chris-codeflow** [comment]
@Archomeda.  I've just submitted a PR to resolve this issue.  See PR #316.

**Comment by chris-codeflow** [comment]
@Archomeda .  I will submit a fix for this issue.
