### ISSUE TITLE
Missing documentation for available configuration for the Azure pipelines task

### ISSUE THREAD

**Issue by hallgeirl** [GitTools/actions#236]
Hi,

I'm having a hard time finding an overview of the available configuration for the Azure pipelines task for gitversion. There is one example: https://github.com/GitTools/actions/blob/master/docs/examples/azure/gitversion/index.md 

Is there any documentation that I have missed? If not, it would be great if an overview of available configuration for this task. Nothing fancy is required - but a list of all inputs would be awesome.

Thanks :)

**Comment by Shafeeqts89** [comment]
Hi,
Same situation here, cannot find any useful documentation for azure pipeline task.

**Comment by chris-codeflow** [comment]
I would like to address this issue.  I will submit a PR with some examples and documentation.

**Comment by arturcic** [comment]
> I would like to address this issue. I will submit a PR with some examples and documentation.

That would be really appreciated

**Comment by chris-codeflow** [comment]
Please can you label this issue with the **documentation** label.  Thanks,

**Comment by chris-codeflow** [comment]
@hallgeirl, please take a look at PR #264 to see if the usage examples I've added are enough.
