### ISSUE TITLE
Using automatic latest version selection does not seem to work

### ISSUE THREAD

**Issue by ptr727** [GitTools/actions#269]
I do not want to keep updating my build scripts for every tool release.
I want to stick to a major version and expect no breaking changes.
If I specify a subversion I'd like the latest to be auto selected.

Works: `uses: gittools/actions/gitversion/execute@v0.9.7`
Does not work: uses: `gittools/actions/gitversion/execute@v0`
Uses an old version: uses: `gittools/actions/gitversion/execute@v0.9`

See here for a relevant discussion:
https://github.community/t/versioning-guidance-for-authoring-and-consuming-actions/138763/3

**Comment by arturcic** [comment]
@ptr727 you could use @master instead, but I would recommend to have a specific version pinned to avoid issues with automatic targeting latest version that might not be compatible, or have a breaking change.

**Comment by ptr727** [comment]
Understood for pre 1.0 release.
Would prefer to use @v1 style and get all version 1 fixes, but v1 must not break backwards compatibility.
Any breaking changes could then bump version, i.e keep @v1 and @v2 separate but both updated.

**Comment by arturcic** [comment]
@ptr727 I have added branch `v0` - will make sure to update it to latest changes when releasing a new version. Can you check it's working for you with `v0`?

**Comment by ptr727** [comment]
I can confirm `@v0` works as expected, thank you.
