### ISSUE TITLE
issue with set-env

### ISSUE THREAD

**Issue by marvel-vella** [GitTools/actions#270]
I have suddenly started to get this error (even with the latest version) 

Error: Unable to process command '::set-env name=GitVersion_CommitDate::2020-11-23' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

it is related to a security issue which has been patched by GitHub and I understand needs to be addressed by GitTools

**Comment by arturcic** [comment]
Can you post here the way you use the actions here? setup and execute?

**Comment by alanta** [comment]
I'm seeing the same issue. Here's my broken build: https://github.com/alanta/Kontent.Statiq/actions/runs/378424537

I tried to update to the latest version of the tasks but that doesn't help.

**Comment by arturcic** [comment]
It's not enough to use the latest task, you should already install the latest gitversion version, please set the versionSpec to 5.x, and you'll get the latest tool installed

**Comment by alanta** [comment]
@arturcic thanks, that solves the issue indeed.
