### ISSUE TITLE
Support Microsoft Net 5.0

### ISSUE THREAD

**Issue by Lukkian** [GitTools/actions#291]
jobs:
   
    build:

    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags. Default: 1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'`

![image](https://user-images.githubusercontent.com/685069/102380916-4e427a80-3fa7-11eb-9fec-b53876152b23.png)

**Comment by arturcic** [comment]
It depends on https://github.com/GitTools/GitVersion/pull/2452

**Comment by arturcic** [comment]
Now that the version 5.6.0 of GitVersion was released with support for .net 5.0 the gittools actions should be able to run. Just make sure to have either the versionSpec set to `5.x` or `5.6.x`
