### ISSUE TITLE
[Feature] provide an option to choose which version type use to update Build.BuildNumber

### ISSUE THREAD

**Issue by quasarea** [GitTools/actions#318]
Currently Build.BuildNumber is updated when running GitVersion target to value of "FullSemVer"

Would be great to be able to chose variable to update to as well as disabling this option. I.e. I tend to use SemVer across the pipeline.

**Comment by arturcic** [comment]
That is a good idea, but first we need to implement it in the GitVersion repo and then expose it in the actions

**Comment by quasarea** [comment]
Oh, I thought that task is doing it on its own, perhaps that is why I could not find it in sources ;) thanks

**Comment by quasarea** [comment]
added feature request for it https://github.com/GitTools/GitVersion/issues/2580
