### ISSUE TITLE
Azure pipelines GitVersion execute task can't find config file

### ISSUE THREAD

**Issue by ianschmitz** [GitTools/actions#335]
When using the `gitversion/execute@0` task, with `useConfigFile: true`, it throws an error that the configuration file can't be found:

![image](https://user-images.githubusercontent.com/6355370/107670575-b92acd80-6c47-11eb-8985-b0ea021c8dce.png)

However, specifying `configFilePath: "GitVersion.yml"` fixes the issue.

**Comment by gaelcolas** [comment]
I concur on the issue & the work around.
