### ISSUE TITLE
Task gitversion/setup - Add support for --add-source 

### ISSUE THREAD

**Issue by Maetis** [GitTools/actions#384]
If Nuget.org is not directly accessible by the build agent (Azure DevOps Server) and it must pass through a "proxy" like Artifactory, the task ```gitversion/setup``` fail.

It could be useful if the task could offer a parameter to specify the source (eg: ```dotnet tool install --add-source *mysource* --global GitVersion.Tool```).

**Comment by arturcic** [comment]
Hi @Maetis if you can send us a PR with that I will check and merge
