### ISSUE TITLE
Value 'json' cannot be parsed as output type, please use 'json' or 'buildserver'

### ISSUE THREAD

**Issue by rducom** [GitTools/actions#57]
I'm having a strange exception with the github action : it can't parse the `/output json` parameter.
I no clue why this happens, since the parsing is case insensitive...
Here's the related build log : https://github.com/rducom/ParallelAsync/pull/1/checks?check_run_id=493761482

 ```
Run gittools/actions/gitversion/execute@v0.9
  with:
    useConfigFile: false
    updateAssemblyInfo: false
  env:
    DOTNET_ROOT: /opt/hostedtoolcache/dncs/3.1.101/x64
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
Command: dotnet-gitversion /home/runner/work/ParallelAsync/ParallelAsync /output json 
/opt/hostedtoolcache/GitVersion.Tool/5.2.0/x64/dotnet-gitversion /home/runner/work/ParallelAsync/ParallelAsync /output json 
Unhandled exception. GitVersion.Exceptions.WarningException: Value 'json' cannot be parsed as output type, please use 'json' or 'buildserver'
   at GitVersion.ArgumentParser.ParseArguments(String[] commandLineArguments) in D:\a\GitVersion\GitVersion\src\GitVersionExe\ArgumentParser.cs:line 320
```

**Comment by arturcic** [comment]
Weird, l'll have a look tomorrow

**Comment by arturcic** [comment]
O checked I can confirm, we need to fix this in the GitVersion itself

**Comment by rducom** [comment]
Fixed with https://github.com/GitTools/actions/releases/tag/v0.9.2
Thanks @arturcic !

**Comment by arturcic** [comment]
> Fixed with https://github.com/GitTools/actions/releases/tag/v0.9.2
> Thanks @arturcic !
You're welcome
