### ISSUE TITLE
Build tasks are spamming warnings on the pipelines (started recently)

### ISSUE THREAD

**Issue by mirandaasm** [GitTools/actions#575]
These build tasks started to spam some warnings on my pipelines (all running on Azure DevOps Services):

##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

They still work fine, but now I'm getting the above warnings on my pipelines. I suppose it's some kind of update on the Azure DevOps Services, which will require the attention from the Build-Task Authors.

**Comment by charleszipp** [comment]
Here's screenshot. This started happening for my task as well. The upgrade steps were pretty straight forward
![image](https://user-images.githubusercontent.com/4292559/141481676-88488fcd-7d12-429a-9248-5b0568d768cc.png)

**Comment by arturcic** [comment]
I'm going to release a new version soon. I would ask you both when it's available to confirm it's fixed

**Comment by arturcic** [comment]
There should be a new version published, please check and please tell me if that fixed the warnings

**Comment by charleszipp** [comment]
confirmed resolved for me

**Comment by mirandaasm** [comment]
same here. resolved for me. 😄

**Comment by arturcic** [comment]
Closing as resolved in v 0.9.11
