### ISSUE TITLE
Projects Targeting Microsoft.NET.Sdk.Worker Sdk

### ISSUE THREAD

**Issue by haydenhancock** [GitTools/actions#679]
Not sure if this is an actual issue or not but we have a project that is targeting .NET Core 3.1 (e.g. `netcoreapp3.1`). The project file is using the `Microsoft.NET.Sdk.Worker` Sdk and the assembly version is not being added to the file when running `gitversion /updateprojectfiles`. 

A stripped down version of the `.csproj` file is below:

```xml
<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.2" />
  </ItemGroup>
</Project>
```

Should GitVersion be able to version these types of projects?

**Comment by arturcic** [comment]
This one should be covered, https://github.com/GitTools/GitVersion/issues/2890
