### ISSUE TITLE
Applying for GitHub publisher verification for "GitTools" Action.

### ISSUE THREAD

**Issue by kenta2097** [GitTools/actions#732]
I’m writing regarding the GH Action [GitTools
](https://github.com/marketplace/actions/gittools)

Our project is starting to migrate the CI/CD to GH Actions and we are interested to use your Actions.
Providing some context, our Security team requires the "Creator Verified by GitHub" badge to start the internal GHA verification process, due to this we are blocked to use unverified Actions.

We would be grateful if you could start the GH Action verification process, as it would help us greatly.

I believe it must improve your impact in the whole GitHub community as a partner organization and also, you are letting us use your actions.

You can find more helpful information in the following articles from GitHub Docs as a good starting point on the process.

[Applying for publisher verification for your organization](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization)
[About marketplace badges](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges)

**Comment by arturcic** [comment]
Good suggestion, I will check how to do that, thanks

**Comment by paveldayneko** [comment]
Very much support, We've been using your tool actively in AzureDevops and now due to GH Actions we can't do that anymore. There is no any dicent alternative.

**Comment by arturcic** [comment]
@asbjornu can you check this one? Can we apply for a publisher verification?

**Comment by asbjornu** [comment]
For some reason, it doesn't look like we have any GitHub Apps registered by the organization?

<img width="944" alt="There must be 1 or more GitHub/OAuth App registered by the organization to request publisher verification" src="https://user-images.githubusercontent.com/12283/192482697-06fef5c9-27fe-41ff-bd0c-7335e8ed0455.png">

**Comment by arturcic** [comment]
we have only a GitHub Action

**Comment by asbjornu** [comment]
I know. But we can't verify the GitTools organization without overcoming this hurdle somehow.

**Comment by kenta2097** [comment]
Hi @arturcic @asbjornu 

We appreciate that the conversation regarding the verification process is started from your side.
Seems the Oauth app register is pretty straightforward
https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app

Cheers

**Comment by asbjornu** [comment]
@kenta2097 registering an OAuth App seems trivial enough, but we have no app to register. We don't want to register an app and give anyone the impression that we have an OAuth App that can be installed and used by anyone, since no such app exists.

**Comment by nmbro** [comment]
I would reach out to github's support, they are usually super helpful, you could ask what the oauth / github app is needed for besides the authentication.

But github apps can be private at least, so that's an option.

**Comment by arturcic** [comment]
![Image](https://github.com/user-attachments/assets/33153f7a-d0a1-4ae3-8606-95c08a97c56e)
