### ISSUE TITLE
Build warning about node12

### ISSUE THREAD

**Issue by samsmithnz** [GitTools/actions#748]
I've started receiving the following warning in GitHub Actions when using these actions:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: gittools/actions, gittools/actions
```

This is running on `ubuntu-latest`, although it's not consistent - the warning must still be rolling out. Any plans to update this action to 16?

**Comment by arturcic** [comment]
het @samsmithnz do you mind filling in a PR with the needed updates? Please update all the action.yml files https://github.com/GitTools/actions/search?q=node12, Thanks

**Comment by samsmithnz** [comment]
@arturcic: I will try. Are there tests I can run too? I admit I'm not that familiar with the internals of the project - an avid user though!

**Comment by samsmithnz** [comment]
@arturcic any idea when there will be another release of this action? There are roughly ~100 closed and merged pull requests since the last release in March...

**Comment by arturcic** [comment]
I will make the release today, hopefully
