### ISSUE TITLE
gitversion/setup doesn't work in GH Actions with ubuntu-22.04

### ISSUE THREAD

**Issue by marvel-vella** [GitTools/actions#768]
Run gittools/actions/gitversion/execute@v0.9.15
Command: dotnet-gitversion /home/runner/work/TravelPoint.Api/TravelPoint.Api /output json /output buildserver
/opt/hostedtoolcache/GitVersion.Tool/5.5.0/x64/dotnet-gitversion /home/runner/work/TravelPoint.Api/TravelPoint.Api /output json /output buildserver
You must install or update .NET to run this application.

App: /opt/hostedtoolcache/GitVersion.Tool/5.5.0/x64/dotnet-gitversion
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '3.1.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.10 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

--------------
As a workaround we have to use ubuntu-20.04 instead of ubuntu-latest

**Comment by arturcic** [comment]
@marvel-vella do you also have a  gittools/actions/gitversion/setup@v0.9.15 there? you should install version 5.11.1 instead, as you have a pretty old version - 5.5.0

**Comment by xenSlayer** [comment]
having same issue. any fix?

**Comment by ColinDabritzQ5id** [comment]
That looks like a different issue to me, with object reference errors? (It may be shallow fetch related, ensure you are doing a full fetch.)

**Comment by arturcic** [comment]
@xenSlayer please check the examples https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/execute/usage-examples.md#execute-gitversion-action-gitversionexecute-usage-examples

On checkout you need to:
```
steps:
  - name: Checkout
    uses: actions/checkout@v2
    with:
      fetch-depth: 0
```
