### ISSUE TITLE
gittools/actions/gitversion/execute@v0.9.14 generates 'set-output' deprecated warning

### ISSUE THREAD

**Issue by david-may-shift** [GitTools/actions#807]
Hello,
we use the following actions in our github actions workflow

- gittools/actions/gitversion/setup@v0.9.14
- gittools/actions/gitversion/execute@v0.9.14

The 'execute' step generates the following warning:

`The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

Is there a plan in place to fix this (or perhaps there is already a fix available)
thanks

**Comment by arturcic** [comment]
@david-may-shift please try version 0.9.15

**Comment by david-may-shift** [comment]
Yes, this is working. My apologies - I should have checked for a new version before raising the issue. 
thanks
