### ISSUE TITLE
version 0.9.15 cannot find GitVersion 6.x

### ISSUE THREAD

**Issue by stormbreakermerika** [GitTools/actions#810]
In our pipeline we are trying to Install GitVersion using the following

![image](https://user-images.githubusercontent.com/55168224/224120138-3a5115d8-9007-4e8c-a143-c3b4a883f95e.png)

We are receiving the following error
![image](https://user-images.githubusercontent.com/55168224/224120352-86a4276c-17cb-467f-b78e-2bb2952377fa.png)
 
 This appears to be the correct syntax?
 
 I did switch us back to 5.x and that appears to have executed properly.  This seems like a bug for the 6.x versioning

**Comment by arturcic** [comment]
It seems it's a bug indeed when installing a preview

**Comment by arturcic** [comment]
@stormbreakermerika when the new release will happen, it will allow to install the pre-release version, but just to let you know, the v6 version introduced breaking changes, that means you might need to adapt your GitVersion.yml file if you have one

**Comment by arturcic** [comment]
Please see https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/setup/usage-examples.md#example-4 on usage

**Comment by stormbreakermerika** [comment]
@arturcic Ok awesome thank you!
