### ISSUE TITLE
Tool 'gitversion.tool' failed to install on self-hosted Ubuntu build agents

### ISSUE THREAD

**Issue by MonkeyTennis** [GitTools/actions#836]
We run the following yaml tasks to set up semantic versioning:

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: 5.9.0
- task: gitversion/execute@0
  displayName: Determine Version

On occasion this fails with the following error:

*****

Tool 'gitversion.tool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
C:\Users\AzDevOps\AppData\Local\Temp\6c8b0eba-4a03-4991-afce-f73ed6bf1c01\restore.csproj : error NU1100: Unable to resolve 'gitversion.tool (>= 5.9.0)' for 'net7.0'.
C:\Users\AzDevOps\AppData\Local\Temp\6c8b0eba-4a03-4991-afce-f73ed6bf1c01\restore.csproj : error NU1100: Unable to resolve 'gitversion.tool (>= 5.9.0)' for 'net7.0/any'.
##[error]Error installing tool

*****

We have noticed that when the error occurs, the pre-requisite step, to install the yaml tasks that enable the build to run, does not download the GitVersion tasks:

Starting: Initialize job
Agent name: '<redacted>'
Agent machine name: '<redacted>'
Current agent version: '3.218.0'
Agent running as: 'AzDevOps'
Prepare build directory.
Set build variables.
Download all required tasks.
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

Whereas, when semantic versioning works, we can see that the tasks are downloaded:

Starting: Initialize job
Agent name: '<redacted>'
Agent machine name: '<redacted>'
Current agent version: '3.218.0'
Agent running as: 'AzDevOps'
Prepare build directory.
Set build variables.
Download all required tasks.
**Downloading task: gitversion/setup (0.10.2)
Downloading task: gitversion/execute (0.10.2)**
Downloading task: PowerShell (2.212.0)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
Finished checking job knob settings.
Start tracking orphan processes.

Any idea why this might be intermittently occurring?

**Comment by arturcic** [comment]
@MonkeyTennis that is because the v5 is targeting .net6.0. There are 2 options you can choose, either install the .net6.0 side by side and then it will run, or you can use the v6 version that is still in development. I'd recommend to install . net 6 for now as a step before installing gitversion
