### ISSUE TITLE
Version variables from GitVersion should be passed through transparently

### ISSUE THREAD

**Issue by asbjornu** [GitTools/actions#86]
I noticed that when trying to access `escapedBranchName` added in GitTools/GitVersion#2157 as `steps.gitversion.outputs.escapedBranchName`, it just came out empty even though ´EscapedBranchName` was written to the console as the default JSON output.

Unless I'm mistaken, it seems like the version variables coming from GitVersion are not passed invisibly through `gittools/actions/gitversion/execute`, but instead explicitly mapped. This reduces the value of `versionSpec` in `gittools/actions/gitversion/setup` since it's not possible to upgrade to a newer version of GitVersion and have its version variables available without also upgrading `gittools/actions/gitversion/execute`.

**Comment by arturcic** [comment]
What solution would you propose to have it more flexible?

**Comment by asbjornu** [comment]
Just a for-loop over the exposed variables, adjusting the keys from `PascalCase` to `camelCase` would do, I suppose?

**Comment by arturcic** [comment]
Interesting, I can play with the idea and see how it works

**Comment by chris-codeflow** [comment]
I don't think this change was required for the following reasons:

- The `steps.gitversion.outputs.<variable name>` syntax is not valid in Azure Pipelines, hence why the variable couldn't be accessed (no variable can be accessed in this way in Azure Pipelines, even if you name the task `gitversion`).
- the GitVersion tool sets the task variables when the **/output buildserver** argument is passed - which is done automatically in the Azure Pipelines task - in the form `GitVersion.<variable>` (see [documentation](https://gitversion.net/docs/build-server-support/build-server/azure-devops)).

In fact, GitVersion sets both a job-scoped and multi-job output variable (of the same name) in the [GenerateSetParameterMessage](https://github.com/GitTools/GitVersion/blob/888bf81c92254f54e462f444b7bac2bdfd9839a5/src/GitVersionCore/BuildAgents/AzurePipelines.cs#L20-L27) method.  This change implemented for this issue now results in another set of job-scoped variables without the `GitVersion.` prefix, which I feel isn't inline with the documentation.

I can say from experience that all the GitVersion variables are available for use in subsequent pipeline steps via the macro reference syntax `$(GitVersion.<variable>)` and can be accessed across both stages and jobs by mapping them into variables using the runtime expression syntax (see [Use outputs in a different job](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-job) and [Use outputs in a different stage](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage).

I am adding usage examples to demonstrate the above, as part of issue #236, but I will be only referencing the variables using the form `GitVersion.<variable>`.

**Comment by chris-codeflow** [comment]
Hello @arturcic and @asbjornu.  Please can you review my comment on this issue and re-open it if you agree.
