### ISSUE TITLE
Unable to find GitVersion.Tool version '5.x'

### ISSUE THREAD

**Issue by LarsStegman** [GitTools/actions#964]
Hello,

our pipelines in Azure use the GitTools extension to install the GitVersion tool. Our pipelines are failing with the following error message:
```
Starting: Install GitVersion
==============================================================================
Task         : Setup GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org/) for projects using Git
Version      : 0.10.2
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
Agent: 'Azure Pipelines'

--------------------------
Acquiring GitVersion.Tool version spec: 5.x
--------------------------
##[error]Unable to find GitVersion.Tool version '5.x'.
Finishing: Install GitVersion
```

They were working fine 3 hours ago.

**Comment by arturcic** [comment]
seems like it's a nuget issue https://status.nuget.org/

**Comment by LarsStegman** [comment]
Time to go home then 😆 , thanks!

**Comment by arturcic** [comment]
Closing it as not related to GitVersion

**Comment by AWilsonBP** [comment]
The NuGet degradation is publishing though. Install is green.

**Comment by codehunter13** [comment]
according to https://status.nuget.org/ only uploading is affected...

**Comment by codehunter13** [comment]
and i can find and download other packagages

**Comment by sdecoodt** [comment]
Same issue here

> according to https://status.nuget.org/ only uploading is affected...

I also wonder what degradation in uploading has to do with this this.

**Comment by LarsStegman** [comment]
Manually setting the version spec to '5.12.0' worked for me to workaround the problem.

**Comment by janode** [comment]
+1, setting the version to `5.12.0`. Seems to be because the search instance at https://azuresearch-usnc.nuget.org/ is having som kind of issue. (https://github.com/GitTools/actions/blob/5bf97605b676c9798ea8a208eb0bcf429c967ee6/src/core/dotnet-tool.ts#L22)

**Comment by arturcic** [comment]
Might be a temporary issue, it seems like now https://azuresearch-usnc.nuget.org/query is working again
